### ISSUE TITLE
Clipboard API Research

### ISSUE THREAD

**Issue by tonsky** [JetBrains/JWM#34] opened 2021-07-12 14:24 UTC
Post here how native clipboard APIs are implemented on different OSes

**Comment by Unruly200** [comment] 2021-07-12 14:28
[Clipboard](Google) 
Duplicate of #

> ``

**Comment by Alex2772** [comment] 2021-07-12 17:44
In X11, a clipboard is not a global instance. All operations to the clipboard occur through a window. This approach does not give any usable advantages or extra features. Only one extra feature i can imagine is possibility to get known which application is currently owning the clipboard to display the message, i. e. "Pasted from Google Chrome" or "Pasted from Telegram". But I lean towards unifying the API because the user of JWM expects only two features - store a string to the clipboard, and get a string from the clipboard.

## Implementation details

Storing to the clipboard (ctrl+c) should be implemented as follows:

1. Make application's window the owner of the clipboard.
2. In application's window, listen to the SelectionRequest. When received, according to the target field, you should either store the type of clipboard data (UTF8_STRING, text/plain, STRING, etc...) to the requestor's buffer or clipboard data itself.
5. Send SelectionNotify event to the requestor.
6. Go to step 2.

Pulling from the clipboard (ctrl+v) should be implemented respectively:

1. Look for clipboard owner. It will be some application's window.
2. Send SelectionRequest to the owner window to request data type.
3. Listen for SelectionNotify. When received, if data type is supported, send the SelectionRequest event to request the data itself.
4. Listen for SelectionNotify to get the data.

Please note that main loop should not be stopped between sending SelectionRequest and listening for SelectionNotify.

**Comment by EgorOrachyov** [comment] 2021-07-19 08:48
In WinAPI, the clipboard is global object, represented from programmer's point of a view as set of functions. Any window in the application can copy from/paste into clipboard something. In windows clipboard data can be in the any format. It is possible to create custom format, register it and get ID, which can be used accross application to identify its own data format. Windows also provides a number of predefined formats, such as bitmap data, sound (wave) data, text and unicode text, etc. 

# Implementation details

Store content into clipboard (ctrl + c) or (ctrl + x):

1. Open clipboard, and associate it with window owner (prevents other applications from clipboard modification). 
2. Empty previouse clipboard data 
3. Allocate handle for data, which will be placed into clipboard
4. Set clipboard data
5. Close clipboard

Get content from clipboard (ctrl + v):

1. Open clipboard, and associate it with window owner
2. Get clipboard data handle (we must provide the ID of expected data format)
3. Lock data
3. Parse data and copy into application internal storage
4. Unlock data 
5. Close clipboard

# Notes

- It is possible to listen to clipboard event (when something pasted into it)
- It is possible to process WM_DESTROYCLIPBOARD if we need to destroy custom format data in the clipboard

# Useful links

[Clipboard API](https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard)
[About the Clipboard](https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-the-clipboard#display-formats)
[Using the Clipboard](https://docs.microsoft.com/en-us/windows/win32/dataxchg/using-the-clipboard#creating-a-clipboard-format-listener)

**Comment by tonsky** [comment] 2021-07-19 11:21
Is it possible to store two or more formats simultateously? E.g. rich text + plain text?
Is there a predefined format for rich text? How does it look like?

**Comment by EgorOrachyov** [comment] 2021-07-19 11:50
As it says:

> After emptying the clipboard, the window places data on the clipboard in as many clipboard formats as possible, ordered from the most descriptive clipboard format to the least descriptive. For each format, the window calls the SetClipboardData function, specifying the format identifier and a global memory handle.

> A window can place more than one clipboard object on the clipboard, each representing the same information in a different clipboard format. When placing information on the clipboard, the window should provide data in as many formats as possible. To find out how many formats are currently used on the clipboard, call the CountClipboardFormats function.

It seems, that each format has its own slot, so it is possible to store multiple values with different formats.

**Comment by EgorOrachyov** [comment] 2021-07-19 11:54
Seems, that it is possible to use rich text format CF_RTF accordingly to this [link](https://docs.microsoft.com/en-us/windows/win32/controls/use-rich-edit-clipboard-operations).

But, CF_RTF is not a standart format, so it must be registered manualy by the application:

> An application can register these formats by using the RegisterClipboardFormat function, specifying the CF_RTF, CF_RTFNOOBJS, and CF_RETEXTOBJ values.

**Comment by SergeevPavel** [comment] 2021-07-20 13:01
about clipboard API, I really like druid approach https://github.com/linebender/druid/blob/master/druid-shell/src/clipboard.rs
please take a look. From my perspective it's not bloated and easy to understand.
AWT has simmilar capabilities, but relations between `DataFlavor` and `Transferable` are quite complicated

**Comment by Alex2772** [comment] 2021-07-20 17:03
> about clipboard API, I really like druid approach https://github.com/linebender/druid/blob/master/druid-shell/src/clipboard.rs
> please take a look. From my perspective it's not bloated and easy to understand.
> AWT has simmilar capabilities, but relations between `DataFlavor` and `Transferable` are quite complicated

Which approach exactly you are talking about?

**Comment by SergeevPavel** [comment] 2021-08-02 10:44
I mean API design, bunch of clear to understand functions instead of complex class hierarchy

**Comment by tonsky** [comment] 2021-08-03 14:15
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/DataFormat.html

https://docs.oracle.com/javase/8/javafx/api/javafx/scene/input/Clipboard.html

https://github.com/linebender/druid/blob/07cc61f930ef7aafbdc7ba30010d18b010acbb31/druid-shell/src/clipboard.rs

**Comment by tonsky** [comment] 2021-08-04 19:00
macOS Clipboard formats: https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc

**Comment by tonsky** [comment] 2021-08-05 12:03
https://docs.google.com/document/d/15g8yz3ChYdZRnCeC0NPGY6xpXrZdaOHQ3BxzMZpHtYU/edit

**Closed** 2021-08-16 14:06 UTC
